///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package key_map

import (
	"fmt"

	"web_demo/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *KeyMap {
	return new(KeyMap)
}

func NewQueryBuilder() *keyMapQueryBuilder {
	return new(keyMapQueryBuilder)
}

func (t *KeyMap) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type keyMapQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *keyMapQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *keyMapQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&KeyMap{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *keyMapQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&KeyMap{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *keyMapQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&KeyMap{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *keyMapQueryBuilder) First(db *gorm.DB) (*KeyMap, error) {
	ret := &KeyMap{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *keyMapQueryBuilder) QueryOne(db *gorm.DB) (*KeyMap, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *keyMapQueryBuilder) QueryAll(db *gorm.DB) ([]*KeyMap, error) {
	var ret []*KeyMap
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *keyMapQueryBuilder) Limit(limit int) *keyMapQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *keyMapQueryBuilder) Offset(offset int) *keyMapQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *keyMapQueryBuilder) WhereId(p mysql.Predicate, value int64) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) WhereIdIn(value []int64) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) WhereIdNotIn(value []int64) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) OrderById(asc bool) *keyMapQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *keyMapQueryBuilder) WhereK(p mysql.Predicate, value string) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "k", p),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) WhereKIn(value []string) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "k", "IN"),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) WhereKNotIn(value []string) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "k", "NOT IN"),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) OrderByK(asc bool) *keyMapQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "k "+order)
	return qb
}

func (qb *keyMapQueryBuilder) WhereVal(p mysql.Predicate, value string) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "val", p),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) WhereValIn(value []string) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "val", "IN"),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) WhereValNotIn(value []string) *keyMapQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "val", "NOT IN"),
		value,
	})
	return qb
}

func (qb *keyMapQueryBuilder) OrderByVal(asc bool) *keyMapQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "val "+order)
	return qb
}
