definitions:
  base.ReturnMsg:
    properties:
      code:
        description: 业务状态码
        type: integer
      data:
        description: 数据
      msg:
        description: 消息
        type: string
      trace:
        description: 请求ID
        type: string
    type: object
  data_obj.UserInfoRes:
    properties:
      email:
        type: string
      ip:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/info:
    get:
      consumes:
      - text/plain
      description: 用户基础信息
      produces:
      - application/json
      responses:
        "200":
          description: 返回数据
          schema:
            allOf:
            - $ref: '#/definitions/base.ReturnMsg'
            - properties:
                Data:
                  $ref: '#/definitions/data_obj.UserInfoRes'
              type: object
      summary: 用户基础信息
      tags:
      - API.user
swagger: "2.0"
