definitions:
  admin.SettingPostRequest:
    properties:
      key:
        description: 键名
        type: string
      val:
        description: 键值
        type: string
    required:
    - key
    - val
    type: object
  base.ReturnMsg:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  code.Failure:
    properties:
      code:
        description: 业务码
        type: integer
      message:
        description: 描述信息
        type: string
    type: object
info:
  contact: {}
paths:
  /api/admin/setting:
    get:
      consumes:
      - text/plain
      description: 获取设置
      parameters:
      - description: 键
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回数据
          schema:
            $ref: '#/definitions/base.ReturnMsg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 获取设置
      tags:
      - API.admin
    post:
      consumes:
      - application/json
      description: 添加设置 一些系统设置保存接口
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/admin.SettingPostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.ReturnMsg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 添加设置
      tags:
      - API.admin
  /index:
    get:
      consumes:
      - text/plain
      description: 返回index html
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 返回index html
      tags:
      - API.html
swagger: "2.0"
